### ISSUE TITLE
Dose this work on hight altitude balloons

### ISSUE THREAD

**Issue by sujaysreedhar** [sparkfun/Copernicus_II_DIP_Module#1]
Dose this specific module work in high altitude flights

**Comment by ToniCorinne** [comment]
We've had customers use them before. Check the module datasheet [here](http://dlnmh9ip6v2uc.cloudfront.net/datasheets/Sensors/GPS/63530-10_Rev-B_Manual_Copernicus-II.pdf) (page 133) to see the altitude/speed limitations for this module.

**Comment by sujaysreedhar** [comment]
i found the speed limit, but i could not find about the altitude limits, is it possible for us to overcome this limitation? and is the framware provided with  this board?

**Comment by mgrusin** [comment]
Google "cocom limits".  This is a feature mandated in all commercial GPS receivers to prevent them from being used in weapons. Such receivers will stop functioning at altitudes of > 60,000' or at > 1000 knots velocity. Many GPS receivers including this one will stop functioning only if BOTH of those limits are exceeded, which means that they WILL function above 60,000' as long as they're not also traveling greater than 1000 knots. This makes them usable for balloon flights, but possibly not for aircraft or rockets.

The GPS module comes with built-in firmware the communicates through a serial port using standard NMEA text messages, or binary-format messages.
